"""
A small fixed control set for check.py: real posts with the label an analyst expects,
from September 2026 (the first 27) and January-May 2026 (rules of labels v7-v10).
Ad markers are removed, so the model itself must spot the ads.
Outcome classes: reklama (ad), boshqa (in the denominator only: non-economic, foreign
or digest), iqt+ / iqt0 / iqt- (economic post counted as positive / neutral / negative).
"""
from config import TONE_THRESHOLD


def outcome(label):
    """What a label does to the index: reklama / boshqa / iqt+ / iqt0 / iqt-."""
    if label["is_ad"]:
        return "reklama"
    if not label["is_economic"] or label["is_digest"] or label["is_foreign"]:
        return "boshqa"
    s = label["sentiment"]
    return "iqt+" if s > TONE_THRESHOLD else "iqt-" if s < -TONE_THRESHOLD else "iqt0"


GOLD = [
    ('@spotuz', 'iqt+', "dollar eng past darajada (so'm mustahkamlandi)",
     '**Курс доллара обновил минимум с августа 2023 года — 11 765 сумов** \nЦентральный банк Узбекистана опубликовал курсы валют на 14 сентября. \n__Подробный график динамики курсов валют доступен на нашем __[__сайте__](https://www.spot.uz/ru/currency/)__.__ \n[Telegram](https://t.me/spotuz) | [Instagram](https://instagram.com/spot.uz) | [YouTube](https://youtube.com/@SpotUz)'),
    ('@daryo', 'iqt-', "dollar 4-kun o'sdi (so'm zaiflashdi)",
     "**O‘zbekistonda dollar kursi ketma-ket to‘rtinchi kun ko‘tarildi** \nMarkaziy bank xorijiy valyutalarning o‘zbek so‘miga nisbatan 19-sentyabrda amalda bo‘ladigan qiymatini eʼlon qildi. \nBatafsil — https://daryo.uz/5xCQRC_vR \n👉 Obuna bo'ling — @daryo"),
    ('@uzdaily', 'iqt+', 'Hyundai bilan yangi loyihalar muhokamasi',
     "**Мирзиёев обсудил с Hyundai новые проекты в Узбекистане** \nШавкат Мирзиёев обсудил с руководителями Hyundai и Kia расширение автопроизводства, локализацию комплектующих и поставки поездов. \n[Читать далее](https://www.uzdaily.uz/ru/mirziioev-obsudil-s-hyundai-novye-proekty-v-uzbekistane/) \n[English](https://t.me/UZDAILYNEWSEN) | [O'zbek tilida](https://t.me/uzdailyuzblot) | [Ўзбек тилида](https://t.me/uzdailynewsuz) | [На русском](https://t.me/UZDAILY) | [iOS](https://apps.ap"),
    ('@uzdaily', 'iqt+', 'Ruminiya bilan hamkorlik kengayadi',
     "**Узбекистан и Румыния расширят сотрудничество в фармацевтике** \nУзбекистан и Румыния обсудили совместное фармпроизводство, трансфер технологий, научные исследования и подготовку специалистов. \n[Читать далее](https://www.uzdaily.uz/ru/uzbekistan-i-rumyniia-rasshiriat-sotrudnichestvo-v-farmatsevtike/) \n[English](https://t.me/UZDAILYNEWSEN) | [O'zbek tilida](https://t.me/uzdailyuzblot) | [Ўзбек тилида](https://t.me/uzdailynewsuz) | [На русском](https://t.me/UZDAILY) | [iOS](htt"),
    ('@gazetauz', 'iqt+', 'Hindistonga uran yetkazish kelishuvi yakunlanmoqda',
     'Узбекистан и Индия находятся на завершающей стадии переговоров о новом долгосрочном соглашении по поставкам урана. По данным МИД Индии, стороны «очень близки» к подписанию документа, который должен продолжить сотрудничество после завершения действующего контракта в 2026 году. \nНью-Дели придаёт этим поставкам особое значение на фоне масштабных планов по развитию атомной энергетики: Индия намерена увеличить её мощность с нынешних 7,9 ГВт до 100 ГВт к 2047 году и по-прежнему в з'),
    ('@spotuz', 'iqt+', 'rejadagi sanoat zonasi (100 qo\'shma korxona)',
     '**В Джизакской области создадут промзону на 200 га по производству стройматериалов для АЭС** \nВ Фаришском районе планируется создать специализированную промышленную зону площадью 200 га для производства строительных материалов для атомной отрасли. На ее территории хотят разместить не менее 100 совместных предприятий и локализовать выпуск продукции по 15 направлениям за счет трансфера технологий. \nИнициатива связана со строительством интегрированной АЭС в Джизакской области и'),
    ('@kunuzofficial', 'iqt+', "2030 yilgi YaIM maqsadi (o'sish)",
     '**2030 йилда 300 млрд долларлик иқтисодиётга айланоламизми? \n** \nПрезидент Шавкат Мирзиёев Мустақиллик байрамидаги нутқида иқтисодий ўсиш бўйича 2030 йил учун янги мақсадли маррани эълон қилди: 300 миллиард долларлик ялпи ички маҳсулот. Иқтисодчи Миркомил Холбоевнинг маълум қилишича, бу – халқаро ташкилотларнинг прогнозларидан унчалик узоқ эмас. Белгиланган маррага етиш учун пандемиядан кейинги даврдаги ўсиш суръатларини сақлаб қолиш керак бўлади. \n👉 https://kun.uz/kr/3145541'),
    ('@uzdaily', 'iqt0', "asosiy stavka o'zgarmadi",
     '**ЦБ Узбекистана сохранил основную ставку на уровне 14%** \nЦентральный банк Узбекистана сохранил основную ставку на уровне 14% годовых на фоне снижения инфляции и сохраняющихся проинфляционных рисков. \n[Читать далее](https://www.uzdaily.uz/ru/tsb-uzbekistana-sokhranil-osnovnuiu-stavku-na-urovne-14-16-09-2026/)'),
    ('@uzdaily', 'iqt0', 'direktor tayinlandi',
     "**«Корзинка» назначила Педро Мартиньо гендиректором** \nСеть супермаркетов Узбекистана «Корзинка» назначила Педро Мартиньо генеральным директором; он имеет более 30 лет опыта в ритейле Европы. \n[Читать далее](https://www.uzdaily.uz/ru/korzinka-naznachila-pedro-martino-gendirektorom/) \n[English](https://t.me/UZDAILYNEWSEN) | [O'zbek tilida](https://t.me/uzdailyuzblot) | [Ўзбек тилида](https://t.me/uzdailynewsuz) | [На русском](https://t.me/UZDAILY) | [iOS](https://apps.apple.co"),
    ('@uzdaily', 'iqt+', 'turistlar soni +21%',
     "**В Узбекистан за восемь месяцев приехали 9,1 млн. туристов** \nВ январе–августе 2026 года Узбекистан посетили более 9,1 млн. иностранных туристов, что на 21,1% больше показателя прошлого года. \n[Читать далее](https://www.uzdaily.uz/ru/v-uzbekistan-za-vosem-mesiatsev-priekhali-91-mln-turistov/) \n[English](https://t.me/UZDAILYNEWSEN) | [O'zbek tilida](https://t.me/uzdailyuzblot) | [Ўзбек тилида](https://t.me/uzdailynewsuz) | [На русском](https://t.me/UZDAILY) | [iOS](https://ap"),
    ('@gazetauz', 'iqt+', "bojxona to'lovi 30% dan 20% ga tushadi",
     'С 1 января 2027 года в Узбекистане снизится единый таможенный платёж за товары, которые физлица ввозят для личных нужд сверх установленных норм беспошлинного ввоза. Ставка уменьшится с 30% до 20% таможенной стоимости превышения. \nОдновременно минимальный размер платежа снизится с 3 до 2 долларов за каждый килограмм товара. Единый платёж заменяет таможенную пошлину, НДС и акцизный налог и применяется независимо от кода ТН ВЭД и страны происхождения товара. \nС 1 июня 2027 года'),
    ('@uzdaily', 'iqt+', 'eksport uchun ombor ochildi',
     "**В аэропорту Инчхона открылся склад для грузов из Узбекистана** \nВ аэропорту Инчхона открылся таможенный склад для грузов из Узбекистана, который позволит упростить поставки и расширить экспорт в Южную Корею. \n[Читать далее](https://www.uzdaily.uz/ru/v-aeroportu-inchkhona-otkrylsia-sklad-dlia-gruzov-iz-uzbekistana/) \n[English](https://t.me/UZDAILYNEWSEN) | [O'zbek tilida](https://t.me/uzdailyuzblot) | [Ўзбек тилида](https://t.me/uzdailynewsuz) | [На русском](https://t.me/UZD"),
    ('@spotuz', 'iqt-', 'propan narxi +65%',
     '**Пропан в Узбекистане подорожал на 65% после отмены потолка цен — до 12,2 млн сумов** \nЦена пропана на товарно-сырьевой бирже за два дня выросла с 7,4 млн до 12,2 млн сумов за тонну. 17 сентября стоимость подскочила на 60,6%, а 18 сентября выросла еще на 2,6%, достигнув нового исторического максимума. Объем продаж за этот период увеличился на 67,2% — до 1114 тонн. \nС 17 сентября на биржевых торгах отменили установленный ранее предел роста цены сжиженного газа. При этом сохра'),
    ('@daryo', 'iqt-', 'suv tariflari oshirildi',
     "**Toshkent viloyatida ichimlik suvi va oqova xizmatlari tariflari oshiriladi** \nQarorda tariflarni oshirish bilan birga iste’molchilarga ko‘rsatiladigan xizmatlar sifatini yaxshilash va yangi narxlar bo‘yicha aholi o‘rtasida tushuntirish ishlarini olib borish vazifasi ham belgilangan. \nBatafsil — https://daryo.uz/jRSMyl_vR \n👉 Obuna bo'ling — @daryo"),
    ('@spotuz', 'iqt-', 'pensiya yoshini oshirish taklifi',
     '⚡️⚡️**В Узбекистане предложили повысить пенсионный возраст на три года** \nМинистерство экономики и финансов предложило постепенно увеличить пенсионный возраст с нынешних 60 лет для мужчин и 55 лет для женщин до 63 и 58 лет соответственно. С 2028 года его планируется повышать на три месяца ежегодно, достигнув нового уровня к 2039 году. \nДля граждан предпенсионного возраста предлагается сохранить ряд гарантий, включая защиту от увольнения или отказа в приеме на работу по причин'),
    ('@kunuzofficial', 'iqt-', 'pensiya stajini oshirish taklifi',
     '**Пенсия учун минимал иш стажи 15 йилгача оширилиши таклиф қилинмоқда – бу нимани англатади? \xa0** \nПенсия тайинлаш учун талаб этиладиган минимал иш стажини босқичма-босқич ошириб, 15 йилга етказиш таклиф қилинмоқда. \nПенсия жамғармаси мутахассислар Kun.uzʼга берган интервюсида нима сабабдан минимал стаж даври узайтирилаётгани, бу пенсия олувчилар учун нимани англатиши ҳақида гапирди.\xa0 \xa0 \n👉 https://kun.uz/kr/76676986 \n[Kun.uz расмий канали](https://t.me/kunuzofficial)'),
    ('@uzdaily', 'iqt-', "1600 MVt avariyaviy o'chish",
     "**В Узбекистане аварийно отключились 1600 МВт мощности** \nНа новой ТЭС EDF в Сырдарьинской области произошло аварийное отключение 1600 МВт, из-за чего в части Узбекистана временно отключилось электричество. \n[Читать далее](https://www.uzdaily.uz/ru/v-uzbekistane-avariino-otkliuchilis-1600-mvt-moshchnosti/) \n[English](https://t.me/UZDAILYNEWSEN) | [O'zbek tilida](https://t.me/uzdailyuzblot) | [Ўзбек тилида](https://t.me/uzdailynewsuz) | [На русском](https://t.me/UZDAILY) | [iO"),
    ('@spotuz', 'iqt-', 'avtomobil sotuvi yillik -30%',
     '**Спрос на\xa0легковые авто за\xa0месяц немного вырос. При этом годовой спад составил 30%** \nПо данным ЦЭИР, в августе узбекистанцы приобрели 79 тысячи автомобилей, из которых легковые составили 62,5 тысячи. Продажи увеличились по сравнению с июлем на 2,2%, при этом в годовом выражении снизились почти на треть. \nВ девяти регионах страны продажи за месяц увеличились, при этом в Ташкенте активность на авторынке упала на 10%. Сильнее всего пострадал вторичный рынок авто — минус 10,8%'),
    ('@daryo', 'boshqa', 'jinoyat ishi',
     "**Toshkent shahar soliq boshqarmasi sobiq boshlig‘iga jinoyat ishi qo‘zg‘atildi** \nYunusjon Nasimjonov o‘zlashtirish yoki rastrata yo‘li bilan talon-toroj qilish hamda mansab vakolatini suiiste’mol qilishda ayblanayotgan bo‘lib, ish sudga oshirildi. \nBatafsil — https://daryo.uz/UYzjrWXDR \n👉 Obuna bo'ling — @daryo"),
    ('@uzdaily', 'boshqa', 'viza uchun pora',
     "**В Ташкенте задержали подозреваемых в продаже виз за $31 тыс.** \nВ Ташкенте задержали двух мужчин, подозреваемых в получении $31,2 тыс. за обещание незаконно оформить визы трем иностранцам. \n[Читать далее](https://www.uzdaily.uz/ru/v-tashkente-zaderzhali-podozrevaemykh-v-prodazhe-viz-za-31-tys/) \n[English](https://t.me/UZDAILYNEWSEN) | [O'zbek tilida](https://t.me/uzdailyuzblot) | [Ўзбек тилида](https://t.me/uzdailynewsuz) | [На русском](https://t.me/UZDAILY) | [iOS](https:/"),
    ('@kunuzofficial', 'boshqa', 'daraxt mashinalar ustiga quladi',
     '**Тошкентда синган дарахт юриб кетаётган машиналар устига тушди** \nТошкент шаҳри марказида синган дарахт ҳаракатланиб кетаётган иккита автомобил устига қулади. Воқеа тонг соат 5:32 да Маҳтумқули кўчасида рўй берган. ФВБ хабарига кўра, жароҳат олганлар йўқ. \nҲолат тезда бартараф этилиб, кўчада автомобиллар ҳаракати тикланган. \n👉 https://kun.uz/kr/79165123 \n[Kun.uz расмий канали](https://t.me/kunuzofficial)'),
    ('@daryo', 'boshqa', "AQSh-Eron to'qnashuvi (xorij)",
     "**AQSH va Eron o‘rtasida to‘qnashuv keskinlashdi: tomonlar bir-biriga yana zarba berdi** **(video)** \nAviazarbalar oqibatida tinch aholi va harbiylar orasida qurbonlar qayd etildi. Xususan, Amerika kuchlari Sirik sohili yaqinida o‘tkazilgan to‘y vaqtida hujum uyushtirdi. Halok bo‘lganlar orasida 4 yoshli bola ham bor. \nBatafsil — https://daryo.uz/JrV2Uxwvg \n👉 Obuna bo'ling — @daryo"),
    ('@kunuzofficial', 'boshqa', 'Saudiya neft quvuri (xorij iqtisodi)',
     '**Саудия Арабистонидаги нефт қувурига берилган зарба жаҳон нефт экспортини хавф остида қолдирди** \nСаудия нефти харидорлари ва трейдерларнинг айтишича, агар нефт қувури иши тикланмаса, Қизил денгиз соҳилида жойлашган Янбу портидаги нефт захиралари атиги беш-етти кунлик импортга етади холос. \nАгентликнинг қайд этишича, ўтган ҳафта нефт нархи июл ойидан бери биринчи марта 100 доллардан ошди. \n👉 https://kun.uz/kr/76660244 \n[Kun.uz расмий канали](https://t.me/kunuzofficial)'),
    ('@daryo', 'boshqa', 'yangiliklar dayjesti',
     '**2-sentyabr kuni e’lon qilingan yangiliklar dayjesti:** \n• O‘zbekistondan naqd valyutani deklaratsiyasiz olib chiqish miqdori 10 ming dollar etib [belgilanadi](https://daryo.uz/2026/09/02/ozbekistondan-naqd-valyutani-deklaratsiyasiz-olib-otish-miqdori-10-ming-dollar-etib-belgilanadi) \n• Janubiy Koreya barcha fuqarolariga SIdan bepul foydalanish [imkonini beradi](https://daryo.uz/2026/09/02/janubiy-koreya-barcha-fuqarolariga-sidan-bepul-foydalanish-imkonini-beradi) \n• Shavkat'),
    ('@uzdaily', 'reklama', 'Synology mahsuloti reklamasi',
     "**Synology RackStation: корпоративные системы хранения данных с возможностью масштабирования** \nНовая серия Synology RackStation объединяет масштабируемые системы хранения и инструменты DSM для работы с данными и бизнес-нагрузками. \n[Читать далее](https://www.uzdaily.uz/ru/synology-rackstation-korporativnye-sistemy-khraneniia-dannykh-s-vozmozhnostiu-masshtabirovaniia/) \n[English](https://t.me/UZDAILYNEWSEN) | [O'zbek tilida](https://t.me/uzdailyuzblot) | [Ўзбек тилида](https:"),
    ('@kunuzofficial', 'reklama', "Kia muddatli to'lov taklifi",
     '**Янги Kia – ўзига хос шартлар асосида: Sonet, Sportage ва K5 учун махсус таклифлар** \nKia бренди янги автомобил харид қилишни осонлаштирмоқда: бир вақтнинг ўзида уч турдаги модел учун бошланғич тўлови 25% дан бошланадиган ва йиллик ставкаси 0% бўлган муддатли тўлов асосида янги молиявий дастурлар мавжуд. \n👉 https://kun.uz/kr/74954883'),
    ('@daryo', 'reklama', 'Milliy bank reklama posti',
     '**O‘zbekiston Milliy banki 35 yoshda!** \n35 yil davomida birga o‘sib, o‘zgarib, hayotingizning bir qismi bo‘lib keldik. \nNBU tarixi — bu nafaqat raqamlar va hisobotlar, balki insonlar va birga boshdan kechirgan lahzalarimizdir. An’analarni asradik, yangiliklar yaratdik, sayohat qildik, biznes ochdik, avtomobil va xonadonlar xarid qildik, muhim qarorlar qabul qildik va maqsadlar sari intildik. \nBizga ishonch bildirayotganingiz va NBU’ni tanlayotganingiz uchun rahmat. \nNBU — 35'),
    # rules of labels v7-v10: real posts of January-May 2026 (added 2026-10-10)
    ('@qalampir', 'iqt+', '10 ta elektropoyezd xaridi (transport, v9)',
     '**Ўзбекистон Чехиядан 10 та электропоезд сотиб олади\n\nБатафсил 👇👇👇\n****https://qalampir.uz/n/135662****\n\nРасмий саҳифаларимизга обуна бўлинг:\n**[**RASMIY**](https://t.me/qalampir)** | **[**LIVE**](https://t.me/qalampirlive)** | **[**SPORT**](https://t.me/qalampirsport)** | **[**TV**](https://t.me/qalampirfm)** | **[**ENGLISH**](https://t.me/qalampir_english)'),
    ('@uzbekistanofficial', 'iqt+', 'chegara postlari 24 soat ishlaydi (savdo, v10)',
     '❗️**Қирғизистон—Ўзбекистон чегарасидаги айрим назорат-ўтказиш пунктлари 24 соатлик режимга ўтди**\n\n20 майдан 1 октябргача қуйидаги чегара пунктлари тун-кун узлуксиз фаолият юритади:\n▪️ “Қадамжой — автойўл”;\n▪️ “Чашма — автойўл”;\n▪️ “Оқ-Қия — автойўл”.\n\nМазкур тартиб фуқаролар ҳаракатини енгиллаштириш ва ёзги мавсумдаги юкламани камайтириш мақсадида жорий этилган.\n\n👉 https://t.me/UZBEKISTANOFFICIAL'),
    ('@qoraxabar', 'iqt+', 'soliq tushumi +24% (soliq oshishi emas, v8)',
     '**❗️****Ўзбекистонда солиқ тушумлари 24 фоизга ўсди**\n\n2026-йилнинг биринчи чорагида солиқ тушумлари 63,6 трлн сўмни ташкил этди. Энг катта улуш фойда солиғига тўғри келди\xa0— 20,4 трлн сўм. Солиқсиз тушумлар, яъни дивиденд тўловлари, бож, йиғим, жарима ва бошқа тўловлардан 3,3 трлн сўм келиб тушган.\n\n👉@QORAXABAR** - Телевизорда кўрсатилмайдиган махфий хабарлар канали!**'),
    ('@daryo', 'iqt+', 'oltin quyma narxi oshdi (oltin eksport, v8)',
     "**O‘zbekistonda 5 grammli quyma oltin narxi birinchi marta 9 mln so‘mdan oshdi**\n\nMarkaziy bank 12-yanvar kuni oltin quymalarini sotish va qadog‘i butligi yoki buzilganiga qarab qayta sotib olish narxlarini e’lon qildi.\n\nBatafsil — https://daryo.uz/lAkupuVvg\n\n👉 Obuna bo'ling — @daryo"),
    ('@daryo', 'iqt-', "aviakompaniyalarga shikoyatlar ko'paydi (v10)",
     "**Centrum Air va Qanot Sharq reyslari kechikishi va chiptalar ortiqcha sotilishi yuzasidan “O‘zaviatsiya”ga so‘rov yuborildi**\n\nRaqobat qo‘mitasi aviaqatnovlar bo‘yicha yo‘lovchilardan kelib tushayotgan murojaatlarni o‘rganib chiqdi. Ular soni o‘tgan yilga nisbatan ortgan.\n\nBatafsil — https://daryo.uz/rtFXIf1vR\n\n👉 Obuna bo'ling — @daryo"),
    ('@daryo', 'iqt-', "Farg'onaga xalqaro reyslar to'xtatiladi (v9)",
     '**Turkish Airlines Farg‘ona va 17 ta xalqaro yo‘nalishga parvozlarni to‘xtatadi**\n\nAviakompaniya Yaqin Sharq, Markaziy Osiyo, Afrika va Yevropadagi ayrim shaharlarga parvozlarni bekor qilib, reyslar sonini qisqartirmoqda.\n\nBatafsil — https://daryo.uz/rrvi5wTvR\n\n👉 Obuna bo‘ling — @daryo'),
    ('@daryo', 'iqt0', 'aeroport direktori tayinlandi (korxona rahbari, v8)',
     "**Alisher Klichev Navoiy xalqaro aeroporti direktori etib tayinlandi**\n\n2020-yilda aeroport rahbari vazifasidan ozod qilingan Alisher Klichev yana shu lavozimga tayinlandi. U ishdan bo‘shatilganda havo porti xodimlari murojaat bilan chiqib, direktorni o‘z lavozimiga qaytarishni so‘ragandi.\n\nBatafsil — https://daryo.uz/yGL9eENDR\n\n👉 Obuna bo'ling — @daryo"),
    ('@daryo', 'boshqa', "oromgoh avtobuslari texnik ko'rigi (transport xavfsizligi, v10)",
     "**O‘zbekistonda o‘quvchilarni yozda oromgohlarga tashiydigan mingdan ortiq avtobus texnik ko‘rikdan o‘tkazildi**\n\nJoriy mavsumda 314 mingdan ortiq bolaning yozgi oromgohlarda dam olishi rejalashtirilgan. Ularning xavfsizligini ta’minlash uchun 692 nafar YPX xodimi jalb etilib, oromgohlarga olib boruvchi yo‘llarda qo‘shimcha xavfsizlik choralari ko‘rilgan.\n\nBatafsil — https://daryo.uz/7HRuvzxvg\n\n👉 Obuna bo'ling — @daryo"),
    ('@kunuzofficial', 'boshqa', 'avtobuslarda konditsioner (transport qulayligi, v10)',
     '**Тошкентдаги автобусларда бугундан бошлаб кондиционерлар ёқилмоқда\n\n**7 майдан бошлаб пойтахтдаги автобусларда совитиш тизимлари босқичма-босқич ишга туширилади.\n\nКондиционери носоз автобуслар йўналишга чиқарилмаслиги, техник носозликлар тезда бартараф этилиши ваъда қилинмоқда.\n\n👉 https://kun.uz/kr/73250491\n\n[Kun.uz расмий канали](https://t.me/kunuzofficial)'),
    ('@oper_uz', 'boshqa', "hayit uchun qo'shimcha reyslar (v10)",
     '❗️**Қурбон ҳайити арафасида Тошкент автовокзалидан 55 та қўшимча рейс йўлга қўйилди**\n\nБайрам олдидан йўловчилар оқими ошиши муносабати билан Тошкент автовокзалидан 55 та қўшимча автобус қатнови ташкил этилди.\n\nМаълум қилинишича, талаб юқори бўлса, яна қўшимча рейслар йўлга қўйилиши мумкин.\n\nШунингдек, Қурбон ҳайити кунлари халқаро аҳамиятдаги автомобил йўлларида ЙПХ ходимлари кучайтирилган тартибда хизмат олиб боради.\n\n✅**@OPER_UZ**** – ОПЕРАТИВ ВА ХАВФЛИ ЯНГИЛИКЛАР КАНАЛИ!**'),
    ('@darakchi', 'boshqa', 'muzlagan dovonda harakat cheklandi (ob-havo, v8)',
     '**“Тахтақорача” довонида ҳаракат вақтинча чекланди**\n\n__Бунга йўлнинг музлагани ва ҳавонинг кескин совиши сабаб бўлган.__\n\n[👉 Батафсил](https://darakchi.uz/uz/210419)\n\n[**Youtube**](https://www.youtube.com/channel/UC7pgDYD_ouB5RwzD1u4Fjxw) | [**Instagram**](https://www.instagram.com/darakchi.uz/) | \n[**Facebook**](https://www.facebook.com/darakchi/) | [**Telegram**](https://t.me/darakchi)'),
    ('@daryo', 'boshqa', 'vazir tayinlandi (davlat organi kadri, v8)',
     '**Qoraqalpog‘istonda kambag‘allikni qisqartirish va bandlik vaziri tayinlandi**\n\n2024-yil mart oyidan buyon ishlab kelayotgan Quanishbay Azerbayev o‘rnini O‘serbay Kazakbayev egalladi.\n\nBatafsil — https://daryo.uz/S80ETRSDR\n\n👉 Obuna bo‘ling — @daryo'),
    ('@uzdaily', 'boshqa', 'harbiy texnika ishlab chiqarish (mudofaa, v8)',
     "**Шавкат Мирзиёев ознакомился с мощностями по производству военной техники**\n\nПрезидент Республики Узбекистан, Верховный Главнокомандующий Вооруженными Силами Шавкат Мирзиёев посетил технопарк в Чирчике, где ознакомился с деятельностью предприятий оборонной промышленности.\n\n[Читать далее](https://www.uzdaily.uz/ru/shavkat-mirziioev-oznakomilsia-s-moshchnostiami-po-proizvodstvu-voennoi-tekhniki/)\n\n[English](https://t.me/UZDAILYNEWSEN) | [O'zbek tilida](https://t.me/uzdailyuzblot) | [Ўзбек тилида](https://t.me/uzdailynewsuz) | [На русском](https://t.me/UZDAILY) | [iOS](https://apps.apple.com/uz/app/uzdaily/id6523431145) |[Android](https://play.google.com/store/apps/details?id=v1.uzdaily.uz&hl=en&pli=1)"),
    ('@spotuz', 'boshqa', 'Turkiyada qurib berilgan uylar (xorijga yordam, v7)',
     '**Узбекистан построил жилой комплекс в\xa0турецкой провинции Хатай после землетрясения**\n\nШавкат Мирзиёев и Реджеп Тайип Эрдоган вручили ключи жильцам комплекса «Узбекистан» в провинции Хатай. Узбекистанские строители возвели 24 дома на 300 квартир в районе, пострадавшем от землетрясения в феврале 2023 года.\n\nТакже президенты дали старт строительству узбекской школы в районе Бакыркёй Стамбула для детей из узбекских семей, проживающих в Турции. Будущая школа станет первым образовательным учреждением Узбекистана за рубежом:\n\nhttps://www.spot.uz/ru/2026/01/30/uzbekistan-hatay/\n\n[Telegram](https://t.me/spotuz)  |  [Instagram](https://instagram.com/spot.uz)  |  [YouTube](https://youtube.com/@SpotUz)'),
    ('@daryouz_dunyo_yangilillar_uz', 'reklama', 'qon bosimi "siri": salomatlik mahsuloti reklamasi (v8)',
     '🚨#Диққат** \n\n ВРАЧЛАР ХАЙРАТДА!!! \n\n❤️ ҚОН-БОСИМИНИ ЙЎҚ ҚИЛИШ СИРИ!\n\nЎзбекистонда ўтган йил давомида қайд этилган ўлимларнинг 61,1% фоизи қон айланиш тизими касалликларидан келиб чиққани аниқланди\n\nAкадемик aйтишича, узоқ умр кўриш сири қон томирларида экан. Агар улар...\n\n****Батафсил малумот:👇****\n        **https://kshop34.site/IhH4Dq/**\n\n⁉️Охиргача ўқинг\n\n(Батафсил кўриш учун юқоридаги хавола устига босинг)**'),
]
